# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0

import os
import re
import traceback
import httpx
import google.auth
from google.genai import client, types
from app.mesh_engine import execute_python_3d_code, generate_sample_mesh, export_mesh_data

SYSTEM_INSTRUCTION = """
You are an expert 3D CAD modeling AI assistant that generates 3D printable objects using Python's `trimesh` library.

YOUR TASK:
Write clean, valid, executable Python code that creates a 3D model assigned to a single variable named `mesh` (of type `trimesh.Trimesh`).

RULES & BEST PRACTICES:
1. Always assign the final 3D model object to a variable named `mesh`.
2. Available pre-imported modules: `trimesh`, `np` (numpy), `math`.
3. Standard 3D geometry builders:
   - Boxes: `trimesh.creation.box(extents=[w, l, h])`
   - Cylinders: `trimesh.creation.cylinder(radius=r, height=h, sections=32)`
   - Spheres: `trimesh.creation.icosphere(subdivisions=3, radius=r)`
   - Cones: `trimesh.creation.cone(radius=r, height=h, sections=32)`
   - Hollow Tubes/Annulus: `trimesh.creation.annulus(r_min=r1, r_max=r2, height=h, sections=32)`
4. Boolean CSG Operations & Transformations:
   - `mesh1.difference(mesh2, engine='manifold')` (Subtractions/Holes)
   - `mesh1.union(mesh2, engine='manifold')` (Unions)
   - `trimesh.util.concatenate([mesh1, mesh2, mesh3])`
   - `mesh.apply_translation([x, y, z])`
   - `mesh.apply_transform(trimesh.transformations.rotation_matrix(angle, [0, 0, 1]))`
   - `mesh.apply_scale(s)`
5. OUTPUT FORMAT:
   Return ONLY valid Python code inside a markdown python block:
   ```python
   # Python CAD code here
   mesh = ...
   ```
"""

def extract_python_code(llm_response_text: str) -> str:
    """Extracts Python code block from LLM response."""
    match = re.search(r"```python\s*(.*?)\s*```", llm_response_text, re.DOTALL)
    if match:
        return match.group(1).strip()
    match = re.search(r"```\s*(.*?)\s*```", llm_response_text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return llm_response_text.strip()

def query_openai_compatible_llm(
    prompt: str,
    base_url: str,
    api_key: str | None = None,
    model_name: str = "qwen2.5-coder",
) -> str:
    """Queries any OpenAI-compatible API (Ollama, vLLM, LM Studio, LocalAI, OpenAI)."""
    headers = {"Content-Type": "application/json"}
    if api_key and api_key.strip():
        headers["Authorization"] = f"Bearer {api_key.strip()}"
        
    url = base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": SYSTEM_INSTRUCTION},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }
    
    with httpx.Client(timeout=60.0) as client_http:
        resp = client_http.post(url, json=payload, headers=headers)
        resp.raise_for_status()
        data = resp.json()
        return data["choices"][0]["message"]["content"]

def query_gemini_llm(
    prompt: str,
    api_key: str | None = None,
    model_name: str = "gemini-2.5-flash",
) -> str:
    """Queries Gemini LLM via Vertex AI ADC or API Key."""
    key = api_key or os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if key and key.strip():
        ai_client = client.Client(api_key=key.strip())
    else:
        try:
            _, project_id = google.auth.default()
        except Exception:
            project_id = os.getenv("GOOGLE_CLOUD_PROJECT", "gemle-gke-dev")
        project_id = project_id or "gemle-gke-dev"
        region = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
        ai_client = client.Client(vertexai=True, project=project_id, location=region)
        
    response = ai_client.models.generate_content(
        model=model_name,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=0.2,
        ),
    )
    return response.text or ""

def generate_cad_model(
    prompt: str,
    current_code: str | None = None,
    model_name: str = "gemini-2.5-flash",
    api_key: str | None = None,
    base_url: str | None = None,
    provider: str = "google",
) -> dict:
    """
    Provider-Agnostic 3D CAD Generation.
    Supports: Google Gemini (Vertex AI / Key), OpenAI, and Self-Hosted / Local LLMs (Ollama, vLLM, LM Studio).
    """
    full_prompt = f"Create 3D Printable CAD Model for Request: {prompt}\n"
    if current_code and current_code.strip():
        full_prompt += f"\nExisting Python Code to Modify:\n```python\n{current_code}\n```\nModify the code according to the request while maintaining a valid `mesh` object."

    # Determine provider logic
    is_custom_endpoint = bool(base_url and base_url.strip())
    provider_type = "self-hosted" if is_custom_endpoint else provider.lower()

    explanation = f"Generated by {provider_type} model ({model_name})"

    def generate_llm_text(text_prompt: str) -> str:
        if is_custom_endpoint:
            return query_openai_compatible_llm(
                prompt=text_prompt,
                base_url=base_url,
                api_key=api_key,
                model_name=model_name,
            )
        else:
            return query_gemini_llm(
                prompt=text_prompt,
                api_key=api_key,
                model_name=model_name,
            )

    # 1. First Call to LLM
    try:
        raw_text = generate_llm_text(full_prompt)
        code = extract_python_code(raw_text)
    except Exception as llm_err:
        log = f"LLM API Error: {str(llm_err)}"
        mesh = generate_sample_mesh("cube")
        code = "# Fallback Box due to API Error\nmesh = trimesh.creation.box(extents=[25, 25, 25])"
        exported = export_mesh_data(mesh)
        return {
            "code": code,
            "explanation": f"API Error: {str(llm_err)}",
            "log": log,
            "stats": exported["stats"],
            "obj_data": exported["obj_data"],
            "stl_bytes": exported["stl_bytes"],
        }

    # 2. Execution & Auto-Correction Reflection Loop
    try:
        mesh, log = execute_python_3d_code(code)
    except Exception as first_error:
        error_log = str(first_error)
        fix_prompt = (
            f"The Python code generated produced an execution error:\n"
            f"```\n{error_log}\n```\n"
            f"Original Request: {prompt}\n"
            f"Faulty Code:\n```python\n{code}\n```\n"
            f"Please fix the code. If using boolean ops use engine='manifold'. Return ONLY valid python code creating a valid `mesh` object."
        )
        try:
            fix_text = generate_llm_text(fix_prompt)
            code = extract_python_code(fix_text)
            mesh, log = execute_python_3d_code(code)
            log = f"Auto-corrected by AI after initial error:\n" + log
        except Exception as retry_error:
            log = f"Execution Error after Retry:\n{traceback.format_exc()}"
            mesh = generate_sample_mesh("cube")
            code = "# Fallback Box\nmesh = trimesh.creation.box(extents=[25, 25, 25])"

    exported = export_mesh_data(mesh)
    
    return {
        "code": code,
        "explanation": explanation,
        "log": log,
        "stats": exported["stats"],
        "obj_data": exported["obj_data"],
        "stl_bytes": exported["stl_bytes"],
    }
