# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0

import os
import re
import traceback
import google.auth
from google.genai import client, types
from app.mesh_engine import execute_python_3d_code, generate_sample_mesh, export_mesh_data

SYSTEM_INSTRUCTION = """
You are an expert 3D CAD modeling AI assistant that generates 3D printable objects using Python's `trimesh` library.

YOUR TASK:
Write clean, valid, executable Python code that creates a 3D model assigned to a single variable named `mesh` (of type `trimesh.Trimesh`).

RULES & BEST PRACTICES:
1. Always assign the final 3D model object to a variable named `mesh`.
2. Available pre-imported modules: `trimesh`, `np` (numpy), `math`.
3. Standard 3D geometry builders:
   - Boxes: `trimesh.creation.box(extents=[w, l, h])`
   - Cylinders: `trimesh.creation.cylinder(radius=r, height=h, sections=32)`
   - Spheres: `trimesh.creation.icosphere(subdivisions=3, radius=r)`
   - Cones: `trimesh.creation.cone(radius=r, height=h, sections=32)`
   - Hollow Tubes/Annulus: `trimesh.creation.annulus(r_min=r1, r_max=r2, height=h, sections=32)`
4. Boolean CSG Operations & Transformations:
   - `mesh1.difference(mesh2, engine='manifold')` (Subtractions/Holes)
   - `mesh1.union(mesh2, engine='manifold')` (Unions)
   - `trimesh.util.concatenate([mesh1, mesh2, mesh3])`
   - `mesh.apply_translation([x, y, z])`
   - `mesh.apply_transform(trimesh.transformations.rotation_matrix(angle, [0, 0, 1]))`
   - `mesh.apply_scale(s)`
5. EXAMPLES:
   # Example: Box with cylindrical hole
   box = trimesh.creation.box(extents=[40, 40, 30])
   hole = trimesh.creation.cylinder(radius=10, height=40)
   mesh = box.difference(hole, engine='manifold')

6. OUTPUT FORMAT:
   Return ONLY valid Python code inside a markdown python block:
   ```python
   # Python CAD code here
   mesh = ...
   ```
"""

def extract_python_code(llm_response_text: str) -> str:
    """Extracts Python code block from LLM response."""
    match = re.search(r"```python\s*(.*?)\s*```", llm_response_text, re.DOTALL)
    if match:
        return match.group(1).strip()
    match = re.search(r"```\s*(.*?)\s*```", llm_response_text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return llm_response_text.strip()

def get_genai_client():
    """Initializes Google GenAI Client with Vertex AI ADC or API Key."""
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if api_key:
        return client.Client(api_key=api_key)
    
    try:
        _, project_id = google.auth.default()
    except Exception:
        project_id = os.getenv("GOOGLE_CLOUD_PROJECT", "gemle-gke-dev")
        
    project_id = project_id or "gemle-gke-dev"
    region = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
    return client.Client(vertexai=True, project=project_id, location=region)

def generate_cad_model(
    prompt: str,
    current_code: str | None = None,
    model_name: str = "gemini-2.5-flash",
) -> dict:
    """
    Calls Real Gemini AI model to generate/modify CAD code, executes it, 
    and returns mesh data with auto-correction loop if code fails.
    """
    ai_client = get_genai_client()

    full_prompt = f"Create 3D Printable CAD Model for Request: {prompt}\n"
    if current_code and current_code.strip():
        full_prompt += f"\nExisting Python Code to Modify:\n```python\n{current_code}\n```\nModify the code according to the request while maintaining a valid `mesh` object."

    explanation = f"Generated by Real Gemini AI ({model_name})"
    
    # 1. First Call to Gemini
    response = ai_client.models.generate_content(
        model=model_name,
        contents=full_prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            temperature=0.2,
        ),
    )
    
    raw_text = response.text or ""
    code = extract_python_code(raw_text)
    
    # 2. Execution & Auto-Correction Reflection Loop
    try:
        mesh, log = execute_python_3d_code(code)
    except Exception as first_error:
        # Self-correction loop: Send traceback error back to Gemini to fix code
        error_log = str(first_error)
        fix_prompt = (
            f"The Python code generated produced an execution error:\n"
            f"```\n{error_log}\n```\n"
            f"Original Request: {prompt}\n"
            f"Faulty Code:\n```python\n{code}\n```\n"
            f"Please fix the code. If using boolean ops use engine='manifold'. Return ONLY valid python code creating a valid `mesh` object."
        )
        try:
            fix_response = ai_client.models.generate_content(
                model=model_name,
                contents=fix_prompt,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_INSTRUCTION,
                    temperature=0.1,
                ),
            )
            code = extract_python_code(fix_response.text or "")
            mesh, log = execute_python_3d_code(code)
            log = f"Auto-corrected by Gemini AI after initial error:\n" + log
        except Exception as retry_error:
            # Fallback if both attempts fail
            log = f"Execution Error after Retry:\n{traceback.format_exc()}"
            mesh = generate_sample_mesh("cube")
            code = "# Fallback Box\nmesh = trimesh.creation.box(extents=[25, 25, 25])"

    exported = export_mesh_data(mesh)
    
    return {
        "code": code,
        "explanation": explanation,
        "log": log,
        "stats": exported["stats"],
        "obj_data": exported["obj_data"],
        "stl_bytes": exported["stl_bytes"],
    }
